/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118392-g0113e30806-20250202"
#endif /* AVUTIL_FFVERSION_H */
